name: Build & Push Image

# on:
#   release:
#     types: 
#       - published
on: [push]
env:
  IMAGE_NAME: $HARBOR_REGISTRY/$HARBOR_NAMESPACE/${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ env.IMAGE_TAG }}
            latest
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: $HARBOR_REGISTRY
          username: ${{ secrets.HARBOR_REGISTRY_USERNAME }}
          password: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "."
          file: "./Dockerfile"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
